services:
  db:
    image: postgres:16
    platform: linux/amd64
    user: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: intern-matching
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
  web:
    build:
      context: .
    command: rails s -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8080:3000"
    depends_on:
      - db
  worker:
    build:
      context: .
    command: bundle exec rake solid_queue:start
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
