default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("RAILS_DB_USER") { "intern-matching" } %>
  password: <%= ENV.fetch("RAILS_DB_PASS") { "password" } %>
  port: <%= ENV.fetch("RAILS_DB_PORT") { "5433" } %>

development:
  <<: *default
  database: intern_matching_development

test:
  <<: *default
  database: intern_matching_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
